sudo: required

lauguage: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t sea5727/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sea5727/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"